version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "04:30"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 100
    labels:
      - "dependencies"
      - "automatic-merge"
