version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: monthly
    groups:
      minor-and-patch-version-updates:
        update-types:
        - "minor"
        - "patch"
