name: Build

on:
  workflow_call:
    inputs:
      changelog-link:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Display branch name
        run: |
          echo "current branch: $GITHUB_REF"
      - name: Init submodules
        run: git submodule update --init --recursive
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 20    # JDK 21 is still unsupported by Kotlin
          check-latest: true
      - name: Set up Gradle cache
        uses: actions/cache@v4
        id: gradle-cache
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Test
        run: ./gradlew clean test
      - name: Assemble
        run: ./gradlew assemble
      - name: Generate Test Report
        uses: mikepenz/action-junit-report@v4
        if: success() || failure()
        with:
          report_paths: '**/TEST-*.xml'
          fail_on_failure: 'false'
      - name: Cleanup Gradle cache
        run: |
          rm -f ~/.gradle/caches/modules-2/modules-2.lock
          rm -f ~/.gradle/caches/modules-2/gc.properties
      - name: Collect release metadata
        if: startsWith(github.ref, 'refs/tags/v')
        id: collect_release_metadata
        run: |
          echo "release_number=$(git tag --points-at HEAD)"  >> $GITHUB_ENV
          echo "release_apk=$(ls app/build/outputs/apk/release/*.apk)" >> $GITHUB_ENV
      - name: Create release
        if: startsWith(github.ref, 'refs/tags/v')
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ env.release_number }}
          body: "see changelog: ${{ inputs.changelog-link }}"
          tag_name: ${{ env.release_number }}
          files: ${{ env.release_apk }}
          token: ${{ secrets.GITHUB_TOKEN }}
