name: Build

on:
  workflow_call:
    inputs:
      earthly-target:
        required: false
        type: string
        default: "+build-and-release-on-github"
      pattern-to-release:
        required: false
        type: string
        default: ""
      junit-report-path:
        required: false
        type: string
        default: '**/TEST-*.xml'

jobs:
  release:
    runs-on: ubuntu-latest
    name: Build
    env:
      FORCE_COLOR: 1
    steps:
      - name: Setup earthly
        uses: earthly/actions-setup@v1
        with:
          version: v0.8.0
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Docker login
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        if: ${{ env.DOCKERHUB_USERNAME != '' && env.DOCKERHUB_TOKEN != '' }}
        run: docker login --username "$DOCKERHUB_USERNAME" --password "$DOCKERHUB_TOKEN"
      - name: Run earthly
        run: earthly --strict --push ${{ inputs.earthly-target }} --PATTERN_TO_RELEASE='${{ inputs.pattern-to-release }}' --GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
      - name: Generate test report
        uses: mikepenz/action-junit-report@v5
        if: ${{ inputs.junit-report-path != '' }}
        with:
          report_paths: ${{ inputs.junit-report-path }}
          fail_on_failure: 'false'
