name: build with earthly

on:
  workflow_call:
    inputs:
      earthly-target:
        required: false
        type: string
        default: "+build-and-release-on-github"
      pattern-to-release:
        required: false
        type: string
        default: ""
      junit-report-path:
        required: false
        type: string
        default: '**/TEST-*.xml'

jobs:
  build-with-earthly:
    runs-on: ubuntu-latest
    env:
      FORCE_COLOR: 1
    steps:
      - name: Setup earthly
        uses: earthly/actions-setup@v1
        with:
          version: v0.8.0
      - name: Check out repository
        uses: actions/checkout@v5
      - name: Docker login
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        if: ${{ env.DOCKERHUB_USERNAME != '' && env.DOCKERHUB_TOKEN != '' }}
        run: docker login --username "$DOCKERHUB_USERNAME" --password "$DOCKERHUB_TOKEN"
      - name: Run earthly
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: |
          export OTHER_ARGS=""
          if [ "$PYPI_TOKEN" != "" ]; then
            echo "adding PyPI token to args"
            export OTHER_ARGS="$OTHER_ARGS --PYPI_TOKEN=$PYPI_TOKEN"
          fi
          earthly --ci --push  ${{ inputs.earthly-target }} --PATTERN_TO_RELEASE='${{ inputs.pattern-to-release }}' --GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} $OTHER_ARGS
